from pylatex import Document, Subsection, Section, Command, Figure, Tabular, MultiRow

section = Section('Eine Tabelle')
bild = "glees.jpg"

class Glees(Document):

    def create_table(self):
        geometry_options = {
             "margin": "2cm",
             "includeheadfoot": True
        }
        doc = Document(page_numbers=True, geometry_options=geometry_options)
        
        with doc.create(Section("Ein Bild vom Veitskopf")):
             with doc.create(Figure(position="h!")) as glees_picture:
                 glees_picture.add_image(bild, width="480px")
                 glees_picture.add_caption("super coole bildbeschreibung")

        test2 = Subsection("Sektoren und Bereiche")
        table2 = Tabular("|c|c|")
        table2.add_hline()
        table2.add_row(["Sektoren","Bereiche"])
        table2.add_hline()
        table2.add_row((MultiRow(2, data="Bleausard"),"Osterinsel"))
        table2.add_hline(2)
        table2.add_row(("","Bleausardblock"))
        table2.add_hline()
        table2.add_row((MultiRow(2, data="Mauerlay"),"Balrock"))
        table2.add_hline(2)
        table2.add_row("", "Rübennase")
        table2.add_hline(2)
        table2.add_row("", "Megalopolis")
        table2.add_hline(2)
        table2.add_row("", "Rush More")
        table2.add_hline(2)
        table2.add_row("", "Supra Arbor")
        table2.add_hline(2)
        table2.add_row("", "Kamel")
        table2.add_hline(2)
        table2.add_row("", "Bescherung")
        table2.add_hline(2)
        table2.add_row("", "Mauerlay")
        table2.add_hline()
        table2.add_row((MultiRow(2, data="Kruzifix"),"Elefant"))
        table2.add_hline(2)
        table2.add_row("", "Kreuzfels")
        table2.add_hline(2)
        table2.add_row("", "Eisheiligen")
        table2.add_hline(2)
        table2.add_row("", "Tiefflieger")
        table2.add_hline(2)
        table2.add_row("", "Löwenherz")
        table2.add_hline()
        table2.add_row((MultiRow(2, data="Lichtung"),"Bromarma"))
        table2.add_hline(2)
        table2.add_row("", "Krokodil")
        table2.add_hline(2)
        table2.add_row("", "Lawine")
        table2.add_hline(2)
        table2.add_row("", "Lichtung")
        table2.add_hline()
        table2.add_row((MultiRow(2, data="Romani Ite Domum"),"The Egg"))
        table2.add_hline(2)
        table2.add_row("", "Forum")
        table2.add_hline(2)
        table2.add_row("", "Römerturm")
        table2.add_hline(2)
        table2.add_row("", "Es")
        table2.add_hline(2)
        table2.add_row("", "Windei")
        table2.add_hline()
        table2.add_row((MultiRow(2, data="Labyrinth"),"Die Macht"))
        table2.add_hline(2)
        table2.add_row("", "Steinzeit")
        table2.add_hline(2)
        table2.add_row("", "Here Be Dragons")
        table2.add_hline()
        table2.add_row((MultiRow(2, data="Terra Incognita"),"Voyger"))
        table2.add_hline(2)
        table2.add_row("", "Humboldt")
        table2.add_hline(2)
        table2.add_row("", "Newton")
        table2.add_hline()
        table2.add_row((MultiRow(2, data="Mordor"),"Kamikaze"))
        table2.add_hline(2)
        table2.add_row("", "Camelot")
        table2.add_hline(2)
        table2.add_row("", "Almost Satan")
        table2.add_hline(2)
        table2.add_row("", "Cosmos")
        table2.add_hline(2)
        table2.add_row("", "Orodruin")
        table2.add_hline(2)
        table2.add_row("", "Barad Dur")
        table2.add_hline(2)
        table2.add_row("", "Gondor")
        table2.add_hline()
        table2.add_row((MultiRow(2, data="West- und Südblöcke"),"Orthank"))
        table2.add_hline(2)
        table2.add_row("", "Macchu Picchu")
        table2.add_hline(2)
        table2.add_row("", "Südblöcke")
        table2.add_hline()
        test2.append(table2)
        section.append(test2)
        doc.append(section)
        doc.generate_pdf("Glees_Versuch1", compiler="pdflatex", clean_tex=False)
        
doc = Glees()
doc.create_table()
